from __future__ import annotations

table_columns = [
    {
        "id": "object_id",
        "fields": {
            "colRef": 411,
            "parentId": 16,
            "parentPos": 411,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "ID",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "name",
        "fields": {
            "colRef": 412,
            "parentId": 16,
            "parentPos": 412,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Nom du projet",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "context",
        "fields": {
            "colRef": 413,
            "parentId": 16,
            "parentPos": 413,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Contexte",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "tags",
        "fields": {
            "colRef": 414,
            "parentId": 16,
            "parentPos": 414,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Etiquettes",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "topics",
        "fields": {
            "colRef": 415,
            "parentId": 16,
            "parentPos": 415,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Th\u00e9matiques",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "topics_comment",
        "fields": {
            "colRef": 416,
            "parentId": 16,
            "parentPos": 416,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commentaire th\u00e9matiques",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "city",
        "fields": {
            "colRef": 417,
            "parentId": 16,
            "parentPos": 417,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commune",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "postal_code",
        "fields": {
            "colRef": 418,
            "parentId": 16,
            "parentPos": 418,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Code postal",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "insee",
        "fields": {
            "colRef": 419,
            "parentId": 16,
            "parentPos": 419,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Code Insee",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "department",
        "fields": {
            "colRef": 420,
            "parentId": 16,
            "parentPos": 420,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "D\u00e9partement",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "department_code",
        "fields": {
            "colRef": 421,
            "parentId": 16,
            "parentPos": 421,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Code d\u00e9partement",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "location",
        "fields": {
            "colRef": 422,
            "parentId": 16,
            "parentPos": 422,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Lieu",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "perimeter",
        "fields": {
            "colRef": 423,
            "parentId": 16,
            "parentPos": 423,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "P\u00e9rim\u00e8tre",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "perimeter_comment",
        "fields": {
            "colRef": 424,
            "parentId": 16,
            "parentPos": 424,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commentaire p\u00e9rim\u00e8tre",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "diagnostic_anct",
        "fields": {
            "colRef": 425,
            "parentId": 16,
            "parentPos": 425,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Diagnostic ANCT",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "diagnostic_anct_attachment",
        "fields": {
            "colRef": 426,
            "parentId": 16,
            "parentPos": 426,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "PJ Diagnostic ANCT",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "diagnostic_is_shared",
        "fields": {
            "colRef": 427,
            "parentId": 16,
            "parentPos": 427,
            "type": "Bool",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Diagnostic partag\u00e9",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "maturity",
        "fields": {
            "colRef": 428,
            "parentId": 16,
            "parentPos": 428,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Niveau de maturit\u00e9",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "maturity__comment",
        "fields": {
            "colRef": 429,
            "parentId": 16,
            "parentPos": 429,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commentaire niveau de maturit\u00e9",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "ownership",
        "fields": {
            "colRef": 430,
            "parentId": 16,
            "parentPos": 430,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Maitre d'ouvrage",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "action",
        "fields": {
            "colRef": 431,
            "parentId": 16,
            "parentPos": 431,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Description de l'action",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "partners",
        "fields": {
            "colRef": 432,
            "parentId": 16,
            "parentPos": 432,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Partenaires",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "budget",
        "fields": {
            "colRef": 433,
            "parentId": 16,
            "parentPos": 433,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Budget pr\u00e9visionnel",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "budget_attachment",
        "fields": {
            "colRef": 434,
            "parentId": 16,
            "parentPos": 434,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "PJ budget pr\u00e9visionnel",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "forecast_financing_plan",
        "fields": {
            "colRef": 435,
            "parentId": 16,
            "parentPos": 435,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Plan de financement pr\u00e9visionnel",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "forecast_financing_plan_attachment",
        "fields": {
            "colRef": 436,
            "parentId": 16,
            "parentPos": 436,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "PJ financement pr\u00e9visionnel",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "final_financing_plan",
        "fields": {
            "colRef": 437,
            "parentId": 16,
            "parentPos": 437,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Plan de financement d\u00e9finitif",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "final_financing_plan_attachment",
        "fields": {
            "colRef": 438,
            "parentId": 16,
            "parentPos": 438,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "PJ financement d\u00e9finitif",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "calendar",
        "fields": {
            "colRef": 439,
            "parentId": 16,
            "parentPos": 439,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Calendrier",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "calendar_attachment",
        "fields": {
            "colRef": 440,
            "parentId": 16,
            "parentPos": 440,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "PJ calendrier",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "administrative_procedures",
        "fields": {
            "colRef": 441,
            "parentId": 16,
            "parentPos": 441,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Proc\u00e9dures administratives",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "dependencies",
        "fields": {
            "colRef": 442,
            "parentId": 16,
            "parentPos": 442,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Liens avec d'autres programmes et contrats",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "dependencies_comment",
        "fields": {
            "colRef": 443,
            "parentId": 16,
            "parentPos": 443,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commentaire liens avec d'autres programmes et contrats",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "evaluation_indicator",
        "fields": {
            "colRef": 444,
            "parentId": 16,
            "parentPos": 444,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Indicateur de suivi et d'\u00e9valuation",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "ecological_transition_compass",
        "fields": {
            "colRef": 445,
            "parentId": 16,
            "parentPos": 445,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Boussole de transition \u00e9cologique",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "extra",
        "fields": {
            "colRef": 446,
            "parentId": 16,
            "parentPos": 445,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Extra column not synced",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
]
