# Generated by Django 5.1.6 on 2025-06-19 06:47
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("projects.Project", "Project"),
                    ("survey.Answer", "Answer"),
                    ("taggit.TaggedItem", "TaggedItem"),
                    ("tasks.Task", "Task"),
                ],
                help_text="Type of the object that triggered the webhook event",
                max_length=32,
            ),
        ),
    ]
