# Generated by Django 6.1 on 2026-09-07 15:24
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_webhookevent_object_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("projects.Project", "Project"),
                    ("survey.Answer", "Answer"),
                    ("taggit.TaggedItem", "TaggedItem"),
                    ("tasks.Task", "Task"),
                    ("home.UserProfile", "UserProfile"),
                ],
                help_text="Type of the object that triggered the webhook event",
                max_length=32,
            ),
        ),
    ]
