# Generated by Django 5.0.6 on 2024-06-18 08:13
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_gristcolumn_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gristconfig",
            name="object_type",
        ),
    ]
