# Generated by Django 5.0.7 on 2024-07-23 10:18
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_gristconfig_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("projects.Project", "Project"),
                    ("survey.Answer", "Answer"),
                    ("taggit.TaggedItem", "TaggedItem"),
                ],
                help_text="Type of the object that triggered the webhook event",
                max_length=32,
            ),
        ),
    ]
