# Generated by Django 5.0.7 on 2024-09-09 09:22
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_webhookevent_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="gristconfig",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
