# Generated by Django 5.1.1 on 2024-09-16 15:13
from __future__ import annotations

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_gristconfig_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GristColumnFilter",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("filter_value", models.CharField(max_length=255)),
                (
                    "grist_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_filters",
                        to="main.gristcolumn",
                    ),
                ),
                (
                    "grist_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_filters",
                        to="main.gristconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grist column filter",
                "verbose_name_plural": "Grist column filters",
                "db_table": "gristcolumnfilter",
            },
        ),
    ]
