# Generated by Django 5.1.6 on 2025-02-26 08:49
from __future__ import annotations

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GristColumn",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("col_id", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=128)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("boolean", "Bool"),
                            ("choice", "Choice"),
                            ("choice_list", "ChoiceList"),
                            ("date", "Date"),
                            ("integer", "Int"),
                            ("numeric", "Numeric"),
                            ("text", "Text"),
                        ],
                        default="text",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grist column",
                "verbose_name_plural": "Grist columns",
                "db_table": "gristcolumn",
                "ordering": ("col_id",),
            },
        ),
        migrations.CreateModel(
            name="GristConfig",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom de la configuration")),
                ("doc_id", models.CharField(max_length=32)),
                ("table_id", models.CharField(max_length=32)),
                ("enabled", models.BooleanField(default=True)),
                ("api_url", models.CharField(max_length=128)),
                ("api_key", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Configuration Grist",
                "verbose_name_plural": "Configurations Grist",
                "db_table": "gristconfig",
                "ordering": ("-created",),
            },
        ),
    ]
