# Generated by Django 5.1.6 on 2025-02-26 08:49
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("grist_connector", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gristconfig",
            name="webhook_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grist_configs",
                to="main.webhookconfig",
            ),
        ),
        migrations.AddField(
            model_name="gristcolumn",
            name="grist_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="grist_connector.gristconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="gristconfig",
            index=models.Index(fields=["enabled"], name="gristconfig_enabled_c1b2e4_idx"),
        ),
        migrations.AddIndex(
            model_name="gristcolumn",
            index=models.Index(fields=["type"], name="gristcolumn_type_fe5e45_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gristcolumn",
            unique_together={("col_id", "grist_config")},
        ),
    ]
