# Generated by Django 5.1.6 on 2025-03-03 15:52
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grist_connector", "0003_alter_gristcolumn_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gristcolumn",
            name="type",
            field=models.CharField(
                choices=[
                    ("boolean", "Bool"),
                    ("choice", "Choice"),
                    ("choice_list", "ChoiceList"),
                    ("date", "Date"),
                    ("datetime", "DateTime:Europe/Amsterdam"),
                    ("integer", "Int"),
                    ("numeric", "Numeric"),
                    ("text", "Text"),
                ],
                default="text",
                max_length=32,
            ),
        ),
    ]
