# Generated by Django 5.1.6 on 2025-04-08 08:53
from __future__ import annotations

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grist_connector", "0004_alter_gristcolumn_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GristReference",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("doc_id", models.CharField(max_length=32)),
                ("table_id", models.CharField(max_length=32)),
                ("api_url", models.CharField(max_length=128)),
                ("api_key", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255, verbose_name="Nom du référentiel")),
            ],
            options={
                "verbose_name": "Référentiel Grist",
                "verbose_name_plural": "Référentiels Grist",
                "db_table": "gristreference",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="gristconfig",
            name="references",
            field=models.ManyToManyField(
                blank=True, related_name="grist_configs", to="grist_connector.gristreference"
            ),
        ),
    ]
