# Generated by Django 5.1.6 on 2025-03-27 14:34
from __future__ import annotations

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LesCommunsConfig",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom de la configuration")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "webhook_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lescommuns_configs",
                        to="main.webhookconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration LesCommuns",
                "verbose_name_plural": "Configurations LesCommuns",
                "db_table": "lescommunsconfig",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="LesCommunsProjet",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("lescommuns_id", models.CharField(max_length=100)),
                ("recoco_id", models.IntegerField()),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lescommuns_connector.lescommunsconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet LesCommuns",
                "verbose_name_plural": "Projets LesCommuns",
                "db_table": "lescommunsprojet",
                "ordering": ("-created",),
            },
        ),
        migrations.AddIndex(
            model_name="lescommunsconfig",
            index=models.Index(fields=["enabled"], name="lescommunsc_enabled_7bdadd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="lescommunsprojet",
            unique_together={("config", "lescommuns_id", "recoco_id")},
        ),
    ]
