# Generated by Django 5.1.6 on 2025-05-13 14:22
from __future__ import annotations

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lescommuns_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lescommunsconfig",
            name="api_key",
            field=models.CharField(default="change_me", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lescommunsprojet",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lescommuns_projects",
                to="lescommuns_connector.lescommunsconfig",
            ),
        ),
        migrations.CreateModel(
            name="LesCommunsProjectSelection",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recoco_id", models.IntegerField()),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lescommuns_project_selections",
                        to="lescommuns_connector.lescommunsconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sélection de projet pour LesCommuns",
                "verbose_name_plural": "Sélections de projet pour LesCommuns",
                "db_table": "lescommunsprojectselection",
                "ordering": ("-created",),
                "unique_together": {("config", "recoco_id")},
            },
        ),
    ]
