# Generated by Django 5.2.3 on 2025-07-01 13:25
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lescommuns_connector", "0003_lescommunsprojet_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="lescommunsprojet",
            name="recommendation_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID de la recommandation associée dans Recoco",
                null=True,
                verbose_name="ID de la recommandation",
            ),
        ),
    ]
