from __future__ import annotations

# TODO: move ton fixture by mocking grist client httpx responses
table_columns = [
    {
        "id": "object_id",
        "fields": {
            "colRef": 411,
            "parentId": 16,
            "parentPos": 411,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "ID",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "name",
        "fields": {
            "colRef": 412,
            "parentId": 16,
            "parentPos": 412,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Nom du projet",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "description",
        "fields": {
            "colRef": 413,
            "parentId": 16,
            "parentPos": 413,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Descritpion du projet",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "tags",
        "fields": {
            "colRef": 414,
            "parentId": 16,
            "parentPos": 414,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Etiquettes",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "topics",
        "fields": {
            "colRef": 415,
            "parentId": 16,
            "parentPos": 415,
            "type": "ChoiceList",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Th\u00e9matiques",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "topics_comment",
        "fields": {
            "colRef": 416,
            "parentId": 16,
            "parentPos": 416,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commentaire th\u00e9matiques",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "city",
        "fields": {
            "colRef": 417,
            "parentId": 16,
            "parentPos": 417,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Commune",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "postal_code",
        "fields": {
            "colRef": 418,
            "parentId": 16,
            "parentPos": 418,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Code postal",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "insee",
        "fields": {
            "colRef": 419,
            "parentId": 16,
            "parentPos": 419,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Code Insee",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "department",
        "fields": {
            "colRef": 420,
            "parentId": 16,
            "parentPos": 420,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "D\u00e9partement",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "department_code",
        "fields": {
            "colRef": 421,
            "parentId": 16,
            "parentPos": 421,
            "type": "Int",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Code d\u00e9partement",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "location",
        "fields": {
            "colRef": 422,
            "parentId": 16,
            "parentPos": 422,
            "type": "Text",
            "widgetOptions": "",
            "isFormula": False,
            "formula": "",
            "label": "Lieu",
            "description": "",
            "untieColIdFromLabel": False,
            "summarySourceCol": 0,
            "displayCol": 0,
            "visibleCol": 0,
            "rules": None,
            "recalcWhen": 0,
            "recalcDeps": None,
        },
    },
    {
        "id": "thematiques",
        "fields": {
            "label": "Thématique(s)",
            "type": "Text",
        },
    },
    {
        "id": "budget_previsionnel",
        "fields": {
            "label": "Budget prévisionnel",
            "type": "Text",
        },
    },
    {
        "id": "maturite_du_projet",
        "fields": {
            "label": "Maturité du projet",
            "type": "Text",
        },
    },
]
