name: "Check, test, deploy production and create a Github release"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check:
    uses: ./.github/workflows/run_check.yml

  test:
    uses: ./.github/workflows/run_tests.yml

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "latest"
            enable-cache: true

        - name: Build the wheel
          run: uv build

        # TODO: do deploy stuff here

  github_release:
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    needs: deploy
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create GitHub release
          uses: ncipollo/release-action@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

