name: "Check and test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/run_check.yml

  test:
    uses: ./.github/workflows/run_tests.yml

  # FIXME: for test purposes, to remove and keep stuff in push_version_tag.yml only
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            version: "latest"
            enable-cache: true

        - name: Build the wheel
          run: uv build

        - name: Copy utils files
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ secrets.AD_HOST }}
            username: ${{ secrets.AD_USERNAME }}
            password: ${{ secrets.AD_PASSWORD }}
            source: "dist/*.whl, manage.py, bin/post_deploy.sh, bin/run_worker.sh, recoco_sync/wsgi.py"
            target: app

        - name: Install the wheel and run the post deploy tasks
          uses: appleboy/ssh-action@v1
          env:
            DJANGO_SETTINGS_MODULE: "recoco_sync.settings.prod"
            DOTENV_FILE: "/home/recocosync/app/.env"
          with:
            host: ${{ secrets.AD_HOST }}
            username: ${{ secrets.AD_USERNAME }}
            password: ${{ secrets.AD_PASSWORD }}
            envs: DJANGO_SETTINGS_MODULE,DOTENV_FILE
            script: |
              cd app
              chmod +x bin/*.sh
              ./bin/post_deploy.sh
