name: "Check, test and deploy to Scalingo (staging)"
on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/run_check.yml

  test:
    uses: ./.github/workflows/run_tests.yml

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Scalingo (staging)
        uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_PRIVATE_KEY }}
          app-name: mec-connect-staging
          known-host: ssh.osc-fr1.scalingo.com
