name: "Check, test, create Github release, and deploy to Scalingo (production)"
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check:
    uses: ./.github/workflows/run_check.yml

  test:
    uses: ./.github/workflows/run_tests.yml

  github_release:
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    needs: test

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create GitHub release
          uses: ncipollo/release-action@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    needs: test

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Deploy to Scalingo (production)
          uses: kolok/deploy-to-scalingo@v1
          with:
            ssh-private-key: ${{ secrets.SCALINGO_SSH_PRIVATE_KEY }}
            app-name: recoco-sync-prod
            known-host: ssh.osc-secnum-fr1.scalingo.com
